name: CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Build
        run: |
          ./gradlew build -x kotlin-styled-next:legacyBrowserTest -x kotlin-styled-next:irBrowserTest -x kotlin-styled-next:printBenchmarkResults

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Tests and benchmarks
        run: |
          ./gradlew test -Ptest
